/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AfrekenenRouteImport } from './routes/afrekenen'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as GroeiRouteImport } from './routes/groei'
import { Route as HulpRouteImport } from './routes/hulp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerkRouteImport } from './routes/merk'
import { Route as OudersRouteImport } from './routes/ouders'
import { Route as OverRouteImport } from './routes/over'
import { Route as PrijzenRouteImport } from './routes/prijzen'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as SpelenRouteImport } from './routes/spelen'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as SpelenIndexRouteImport } from './routes/spelen.index'
import { Route as SpelenGameIdRouteImport } from './routes/spelen.$gameId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AfrekenenRoute = AfrekenenRouteImport.update({
  id: '/afrekenen',
  path: '/afrekenen',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const GroeiRoute = GroeiRouteImport.update({
  id: '/groei',
  path: '/groei',
  getParentRoute: () => rootRouteImport,
} as any)
const HulpRoute = HulpRouteImport.update({
  id: '/hulp',
  path: '/hulp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerkRoute = MerkRouteImport.update({
  id: '/merk',
  path: '/merk',
  getParentRoute: () => rootRouteImport,
} as any)
const OudersRoute = OudersRouteImport.update({
  id: '/ouders',
  path: '/ouders',
  getParentRoute: () => rootRouteImport,
} as any)
const OverRoute = OverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijzenRoute = PrijzenRouteImport.update({
  id: '/prijzen',
  path: '/prijzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelenRoute = SpelenRouteImport.update({
  id: '/spelen',
  path: '/spelen',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelenIndexRoute = SpelenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpelenRoute,
} as any)
const SpelenGameIdRoute = SpelenGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => SpelenRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/afrekenen': typeof AfrekenenRoute
  '/cookies': typeof CookiesRoute
  '/groei': typeof GroeiRoute
  '/hulp': typeof HulpRoute
  '/login': typeof LoginRoute
  '/merk': typeof MerkRoute
  '/ouders': typeof OudersRoute
  '/over': typeof OverRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/school': typeof SchoolRoute
  '/spelen': typeof SpelenRouteWithChildren
  '/voorwaarden': typeof VoorwaardenRoute
  '/spelen/$gameId': typeof SpelenGameIdRoute
  '/spelen/': typeof SpelenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/afrekenen': typeof AfrekenenRoute
  '/cookies': typeof CookiesRoute
  '/groei': typeof GroeiRoute
  '/hulp': typeof HulpRoute
  '/login': typeof LoginRoute
  '/merk': typeof MerkRoute
  '/ouders': typeof OudersRoute
  '/over': typeof OverRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/school': typeof SchoolRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/spelen/$gameId': typeof SpelenGameIdRoute
  '/spelen': typeof SpelenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/afrekenen': typeof AfrekenenRoute
  '/cookies': typeof CookiesRoute
  '/groei': typeof GroeiRoute
  '/hulp': typeof HulpRoute
  '/login': typeof LoginRoute
  '/merk': typeof MerkRoute
  '/ouders': typeof OudersRoute
  '/over': typeof OverRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/school': typeof SchoolRoute
  '/spelen': typeof SpelenRouteWithChildren
  '/voorwaarden': typeof VoorwaardenRoute
  '/spelen/$gameId': typeof SpelenGameIdRoute
  '/spelen/': typeof SpelenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/afrekenen'
    | '/cookies'
    | '/groei'
    | '/hulp'
    | '/login'
    | '/merk'
    | '/ouders'
    | '/over'
    | '/prijzen'
    | '/privacy'
    | '/school'
    | '/spelen'
    | '/voorwaarden'
    | '/spelen/$gameId'
    | '/spelen/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/afrekenen'
    | '/cookies'
    | '/groei'
    | '/hulp'
    | '/login'
    | '/merk'
    | '/ouders'
    | '/over'
    | '/prijzen'
    | '/privacy'
    | '/school'
    | '/voorwaarden'
    | '/spelen/$gameId'
    | '/spelen'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/afrekenen'
    | '/cookies'
    | '/groei'
    | '/hulp'
    | '/login'
    | '/merk'
    | '/ouders'
    | '/over'
    | '/prijzen'
    | '/privacy'
    | '/school'
    | '/spelen'
    | '/voorwaarden'
    | '/spelen/$gameId'
    | '/spelen/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AfrekenenRoute: typeof AfrekenenRoute
  CookiesRoute: typeof CookiesRoute
  GroeiRoute: typeof GroeiRoute
  HulpRoute: typeof HulpRoute
  LoginRoute: typeof LoginRoute
  MerkRoute: typeof MerkRoute
  OudersRoute: typeof OudersRoute
  OverRoute: typeof OverRoute
  PrijzenRoute: typeof PrijzenRoute
  PrivacyRoute: typeof PrivacyRoute
  SchoolRoute: typeof SchoolRoute
  SpelenRoute: typeof SpelenRouteWithChildren
  VoorwaardenRoute: typeof VoorwaardenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afrekenen': {
      id: '/afrekenen'
      path: '/afrekenen'
      fullPath: '/afrekenen'
      preLoaderRoute: typeof AfrekenenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groei': {
      id: '/groei'
      path: '/groei'
      fullPath: '/groei'
      preLoaderRoute: typeof GroeiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hulp': {
      id: '/hulp'
      path: '/hulp'
      fullPath: '/hulp'
      preLoaderRoute: typeof HulpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merk': {
      id: '/merk'
      path: '/merk'
      fullPath: '/merk'
      preLoaderRoute: typeof MerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouders': {
      id: '/ouders'
      path: '/ouders'
      fullPath: '/ouders'
      preLoaderRoute: typeof OudersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over': {
      id: '/over'
      path: '/over'
      fullPath: '/over'
      preLoaderRoute: typeof OverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijzen': {
      id: '/prijzen'
      path: '/prijzen'
      fullPath: '/prijzen'
      preLoaderRoute: typeof PrijzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spelen': {
      id: '/spelen'
      path: '/spelen'
      fullPath: '/spelen'
      preLoaderRoute: typeof SpelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spelen/': {
      id: '/spelen/'
      path: '/'
      fullPath: '/spelen/'
      preLoaderRoute: typeof SpelenIndexRouteImport
      parentRoute: typeof SpelenRoute
    }
    '/spelen/$gameId': {
      id: '/spelen/$gameId'
      path: '/$gameId'
      fullPath: '/spelen/$gameId'
      preLoaderRoute: typeof SpelenGameIdRouteImport
      parentRoute: typeof SpelenRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpelenRouteChildren {
  SpelenGameIdRoute: typeof SpelenGameIdRoute
  SpelenIndexRoute: typeof SpelenIndexRoute
}

const SpelenRouteChildren: SpelenRouteChildren = {
  SpelenGameIdRoute: SpelenGameIdRoute,
  SpelenIndexRoute: SpelenIndexRoute,
}

const SpelenRouteWithChildren =
  SpelenRoute._addFileChildren(SpelenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AfrekenenRoute: AfrekenenRoute,
  CookiesRoute: CookiesRoute,
  GroeiRoute: GroeiRoute,
  HulpRoute: HulpRoute,
  LoginRoute: LoginRoute,
  MerkRoute: MerkRoute,
  OudersRoute: OudersRoute,
  OverRoute: OverRoute,
  PrijzenRoute: PrijzenRoute,
  PrivacyRoute: PrivacyRoute,
  SchoolRoute: SchoolRoute,
  SpelenRoute: SpelenRouteWithChildren,
  VoorwaardenRoute: VoorwaardenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
